version: "3"

services:
  db:
    container_name: rails-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - ./src/db/mysql_volumes:/var/lib/mysql

  web:
    container_name: rails-app
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./src:/app
    ports:
      - 3000:3000
    depends_on:
      - db

  # adminer:
  #   container_name: adminer
  #   image: adminer:4.8.1
  #   ports:
  #     - "8081:8080"
  #   depends_on:
  #     - db
